spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
urlUser: http://localhost:8093
